name: Lint BrightScript

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"
          cache: "yarn"
      - run: yarn install
      - run: yarn lint
