name: Release

on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: "Prerelease"
        required: true
        default: false
        type: boolean
      draft:
        description: "Draft"
        required: true
        default: false
        type: boolean
      version-increment-type:
        description: "Which part of the version to increment:"
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
        default: "patch"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Check out the repo with credentials that can bypass branch protection, and fetch git history instead of just latest commit
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.AUTOMATION_USER_TOKEN }}
          fetch-depth: 0

      - uses: DevCycleHQ/release-action/prepare-release@v2.3.0
        id: prepare-release
        with:
          github-token: ${{ secrets.AUTOMATION_USER_TOKEN }}
          prerelease: ${{ github.event.inputs.prerelease }}
          draft: ${{ github.event.inputs.draft }}
          version-increment-type: ${{ github.event.inputs.version-increment-type }}

      - name: Run make bundle
        run: make bundle VERSION=${{ steps.prepare-release.outputs.next-release-tag }}

      - name: Upload package.zip
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: package-${{ steps.prepare-release.outputs.next-release-tag }}.zip

      - uses: DevCycleHQ/release-action/create-release@v2.3.0
        id: create-release
        with:
          github-token: ${{ secrets.AUTOMATION_USER_TOKEN }}
          tag: ${{ steps.prepare-release.outputs.next-release-tag }}
          target: main
          prerelease: ${{ github.event.inputs.prerelease }}
          draft: ${{ github.event.inputs.draft }}
          changelog: ${{ steps.prepare-release.outputs.changelog }}
          files: |
            package-${{ steps.prepare-release.outputs.next-release-tag }}.zip
      - name: Display link to release
        run: |
          echo "::notice title=Release ID::${{ steps.create-release.outputs.release-id }}"
          echo "::notice title=Release URL::${{ steps.create-release.outputs.release-url }}"
